# Generated by Django 2.1.5 on 2019-02-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
